#ifndef LUMINANCE_HISTOGRAM_COMMON_HLSL
#define LUMINANCE_HISTOGRAM_COMMON_HLSL

static const uint LUMINANCE_HISTOGRAM_BINS = 256;
static const float LUMINANCE_HISTOGRAM_MIN_LOG = -16.0;
static const float LUMINANCE_HISTOGRAM_MAX_LOG = 16.0;

#endif  // LUMINANCE_HISTOGRAM_COMMON_HLSL
