#define DIFFUSE_GI_USE_RESTIR 1
#define DIFFUSE_GI_BRDF_SAMPLING 0
#define DIFFUSE_GI_SAMPLING_FULL_SPHERE 0
#define RESTIR_TEMPORAL_M_CLAMP 10.0
#define RESTIR_RESERVOIR_W_CLAMP 3.0
#define RESTIR_USE_PATH_VALIDATION !true