#ifndef LUMINANCE_HISTOGRAM_COMMON_HLSL
#define LUMINANCE_HISTOGRAM_COMMON_HLSL

static const uint LUMINANCE_HISTOGRAM_BIN_COUNT = 256;
static const float LUMINANCE_HISTOGRAM_MIN_LOG2 = -16.0;
static const float LUMINANCE_HISTOGRAM_MAX_LOG2 = 16.0;

#endif  // LUMINANCE_HISTOGRAM_COMMON_HLSL
