[package]
name = "rust-shaders"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["lib", "dylib"]
test = false
doctest = false

[dependencies]
spirv-std = { version = "0.4.0-alpha.12", features = ["glam"] }
spirv-std-macros = "0.4.0-alpha.12"